### PR TITLE
Reload: "data" is already destructured by language and namespace.

### PR DESCRIPTION
**Pull request by jorge-marques**
This seems to fix the reload functionality for me (#5).
Would really appreciate it if one of the maintainers could review it.

### CODE REVIEW

**Comment by jamuhl** [comment]
omg...i totally forgot about this open issue...sorry for that.

**Comment by jorge-marques** [comment]
@jamuhl Any chance of a release in the coming days?

**Comment by jamuhl** [comment]
yes...will publish an update asap...today

**Comment by jamuhl** [comment]
should be in i18next-node-remote-backend@1.0.1

**Comment by jorge-marques** [comment]
👍 Thank you.

**Pull request merged**
