### PR TITLE
add support for loadPath as a function

### PR DESCRIPTION
**Pull request by Tushkiz**
add support for `loadPath` as a `function` like `i18next-xhr-backend`
Had to update `gulp-git` because build was failing
Let me know if I should update `package.json` to have absolute version numbers

### CODE REVIEW

**Comment by jamuhl** [comment]
What's the use case for this?

**Comment by Tushkiz** [comment]
I wanted to customize path at runtime e.g local-server for dev and cdn for production.
But I found out that this function is evaluated just once, haven't been able to get it to work.
Shall I mark this PR as work-in-progress?

**Comment by jamuhl** [comment]
i'm unsure...biggest problem i see we would have to port this to all other backend implementations provided to keep it in line.

So guess i would prefer "closing" this and let this be done in a custom backend...not hard to create a own for this use case.

**Comment by Tushkiz** [comment]
I am closing this and would appreciate if have any pointers to share.
Thanks

**Comment by jamuhl** [comment]
https://www.i18next.com/misc/creating-own-plugins#backend

**Pull request closed without merging**
