### PR TITLE
added xhr function as an option

### PR DESCRIPTION
**Pull request by sSala**

### CODE REVIEW

**Comment by jamuhl** [comment]
what is your use case for this...? just out of curiosity...

**Comment by sSala** [comment]
We need to use a different XHR function with [axios](https://github.com/axios/axios) and some custom interceptors

**Comment by jamuhl** [comment]
can you undo changes in the .gitignore? not sure but that ends in a conflict...so I can't merge the PR here

**Comment by jamuhl** [comment]
published in i18next-node-remote-backend@1.1.0

**Comment by martpie** [comment]
`1.1.0` breaks SSR on my Next.js website (1.0.0 is fine). Is there something I missed and we need to provide a custom ajax function now?

**Comment by jamuhl** [comment]
hm...looking at this change - I don't see a difference -> should work as before when not passing in a custom ajax function...

**Comment by martpie** [comment]
thanks, I'll investigate what goes wrong, maybe a sub-dep problem

**Pull request merged**
